### PR TITLE
Created the Register, Login views and serializers

### LINKED ISSUE #9: Implement Login Serializers
This should be created under the **User control** app
LoginSerializer should inherit from ModelSeriailzer.
The serializer model should be set to the Django User Model.
The LoginSerializer should accept only the email and password field and not all the fields in the User Model

### IF YOU HAVE ANY QUESTIONS COMMENT ON THIS ISSUE

### LINKED ISSUE #10: Implement User Serializer
This should be created under the **User control** app
**UserSerializer** should inherit from **ModelSeriailzer.**
The serializer model should be set to the Django User Model
The **UserSerializer** should accept only _username, email and password fields_

### IF YOU HAVE ANY QUESTIONS COMMENT ON THIS ISSUE

### LINKED ISSUE #12: Implement User Views
**UserViewSet** should inherit from **ModelViewSet**.
The serializer class should be set to the **UserSerializer**
The model should be set to User Model

###Note: IF YOU HAVE ANY QUESTIONS COMMENT ON THIS ISSUE

### LINKED ISSUE #13: Implement Login View
**LoginViewSet** should inherit from **ModelViewSet**.
The serializer class should be set to the **LoginSerializer**
The model should be set to User Model
This view method should be set to **POST** only

Overwrite the create method and generate an access token using the provided email and password. The access token should expire in 5 hours

This view should return JSON in this format  

```
{ 
  "access_token": "generated access token string"
}
```

###Note: IF YOU HAVE ANY QUESTIONS COMMENT ON THIS ISSUE

### LINKED ISSUE #14: Implement Logout View
The serializer class should be set to the **LogoutSerializer**
The model should be set to User Model
This view method should be set to **GET** only

### Note: IF YOU HAVE ANY QUESTIONS COMMENT ON THIS ISSUE

### LINKED ISSUE #19: Implement Login, and Users Related URLS

### PR DESCRIPTION
**Pull request by TheDuke2**
Created the Register, Login views and serializers using knox

### CODE REVIEW

**Comment by danthecm** [comment]
This looks nice. But You didn't fetch the latest dev branch updates before creating your new branch. So your requirements.txt file doesn't include some of the latest packages i installed

**Comment by danthecm** [comment]
Also @TheDuke2 have you tested it out with post man that everything works if that's the case also create the logout view and test so I can merge

**Comment by TheDuke2** [comment]
I have made the changes you request, put review. I am still working on the logout tho.

**Review by Bagais — APPROVED** [review]

**Review by danthecm — APPROVED** [review]
Fantastic great job @TheDuke2

**Pull request merged**
